# SPDX-FileCopyrightText: 2026 Lukas Backström <lukas@erlang.org>
# SPDX-License-Identifier: Apache-2.0

defmodule AwfyTest.SyncDrift do
  @moduledoc """
  The cross-OTP bundle is intentionally not a path-dep of the
  runner (PLAN/TARGET_ELIXIR_RUNNER_PLAN.md decision #10), so
  shared helpers (SuiteSlim, BatchAdjust) live in
  `lib/awfy/...` and get *copied* into
  `apps/awfy_target_runner/lib/awfy/_synced/` at bundle-build time
  by `bin/build-target-bundle.sh`.

  Before that codegen step existed (and the comment-pinning that
  preceded it), two byte-identical copies sat in the tree —
  `Awfy.SuiteSlim` in the runner and an inlined version in
  `target_runner.ex` — and `adjust_for_batching/2` was duplicated
  the same way. PLAN/INFRA_REFACTOR.md § 2.

  This test catches drift between the canonical source and the
  in-tree synced copy. If someone edits the canonical but forgets
  to re-run the bundle build (or runs it but doesn't commit the
  resulting diff), this test fails at PR time instead of months
  later as a silent measurement skew.
  """

  use ExUnit.Case, async: true

  @sync_pairs [
    {"lib/awfy/suite_slim.ex", "apps/awfy_target_runner/lib/awfy/_synced/suite_slim.ex"},
    {"lib/awfy/measure/batch_adjust.ex", "apps/awfy_target_runner/lib/awfy/_synced/batch_adjust.ex"}
  ]

  for {canonical, synced} <- @sync_pairs do
    test "synced copy of #{canonical} matches the canonical source" do
      canonical_bin = File.read!(unquote(canonical))
      synced_bin = File.read!(unquote(synced))

      assert canonical_bin == synced_bin, """
      Drift between #{unquote(canonical)} and #{unquote(synced)}.

      The synced copy is auto-generated by `bin/build-target-bundle.sh`.
      Either re-run the bundle build, or `cp` the canonical file into
      the synced path manually:

          cp #{unquote(canonical)} #{unquote(synced)}
      """
    end
  end
end
